<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://webservice.model.prueba.infosgroup.com/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" name="ConteoWebService" targetNamespace="http://webservice.model.prueba.infosgroup.com/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://192.168.20.150:9999/ViducWebApp/ConteoWebService?xsd=1" namespace="http://webservice.model.prueba.infosgroup.com/" />
    </xsd:schema>
  </types>
  <message name="findUbicacionesUsuario">
    <part name="parameters" element="tns:findUbicacionesUsuario" />
  </message>
  <message name="findUbicacionesUsuarioResponse">
    <part name="parameters" element="tns:findUbicacionesUsuarioResponse" />
  </message>
  <message name="registrarConteoFisico">
    <part name="parameters" element="tns:registrarConteoFisico" />
  </message>
  <message name="registrarConteoFisicoResponse">
    <part name="parameters" element="tns:registrarConteoFisicoResponse" />
  </message>
  <portType name="ConteoWebService">
    <operation name="findUbicacionesUsuario">
      <input wsam:Action="http://webservice.model.prueba.infosgroup.com/ConteoWebService/findUbicacionesUsuarioRequest" message="tns:findUbicacionesUsuario" />
      <output wsam:Action="http://webservice.model.prueba.infosgroup.com/ConteoWebService/findUbicacionesUsuarioResponse" message="tns:findUbicacionesUsuarioResponse" />
    </operation>
    <operation name="registrarConteoFisico">
      <input wsam:Action="http://webservice.model.prueba.infosgroup.com/ConteoWebService/registrarConteoFisicoRequest" message="tns:registrarConteoFisico" />
      <output wsam:Action="http://webservice.model.prueba.infosgroup.com/ConteoWebService/registrarConteoFisicoResponse" message="tns:registrarConteoFisicoResponse" />
    </operation>
  </portType>
  <binding name="ConteoWebServicePortBinding" type="tns:ConteoWebService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="findUbicacionesUsuario">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="registrarConteoFisico">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="ConteoWebService">
    <port name="ConteoWebServicePort" binding="tns:ConteoWebServicePortBinding">
      <soap:address location="http://192.168.20.150:9999/ViducWebApp/ConteoWebService" />
    </port>
  </service>
</definitions>