//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5420.
// 
namespace viducWMS.ws_Conteo {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConteoWebServicePortBinding", Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class ConteoWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ConteoWebService() {
            if (clsLeerXML.wsConteo != "")
            {
                this.Url = clsLeerXML.wsConteo;
            }
            else
            {
                this.Url = "http://192.168.20.150:9999/ViducWebApp/ConteoWebService";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.model.prueba.infosgroup.com/", ResponseNamespace="http://webservice.model.prueba.infosgroup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public invFisicoDet[] findUbicacionesUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario) {
            object[] results = this.Invoke("findUbicacionesUsuario", new object[] {
                        usuario});
            return ((invFisicoDet[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindUbicacionesUsuario(string usuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findUbicacionesUsuario", new object[] {
                        usuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public invFisicoDet[] EndfindUbicacionesUsuario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((invFisicoDet[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.model.prueba.infosgroup.com/", ResponseNamespace="http://webservice.model.prueba.infosgroup.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool registrarConteoFisico([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long compania, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime fechaConteo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaConteoSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long bodega, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long secuencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string producto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long anaquel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string area, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long nivel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cantidadContada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long no_inventario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long no_listado) {
            object[] results = this.Invoke("registrarConteoFisico", new object[] {
                        compania,
                        fechaConteo,
                        fechaConteoSpecified,
                        bodega,
                        secuencia,
                        producto,
                        anaquel,
                        area,
                        nivel,
                        cantidadContada,
                        no_inventario,
                        no_listado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginregistrarConteoFisico(long compania, System.DateTime fechaConteo, bool fechaConteoSpecified, long bodega, long secuencia, string producto, long anaquel, string area, long nivel, long cantidadContada, long no_inventario, long no_listado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registrarConteoFisico", new object[] {
                        compania,
                        fechaConteo,
                        fechaConteoSpecified,
                        bodega,
                        secuencia,
                        producto,
                        anaquel,
                        area,
                        nivel,
                        cantidadContada,
                        no_inventario,
                        no_listado}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndregistrarConteoFisico(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class invFisicoDet {
        
        private long anaquelField;
        
        private bool anaquelFieldSpecified;
        
        private string areaField;
        
        private long cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private long cantidadSistemaField;
        
        private bool cantidadSistemaFieldSpecified;
        
        private long codBodegaField;
        
        private bool codBodegaFieldSpecified;
        
        private string codigoField;
        
        private string descripcionField;
        
        private invFisico invFisicoField;
        
        private invFisicoDetPK invFisicoDetPKField;
        
        private long nivelField;
        
        private bool nivelFieldSpecified;
        
        private string umedidaField;
        
        private usuario usuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long anaquel {
            get {
                return this.anaquelField;
            }
            set {
                this.anaquelField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anaquelSpecified {
            get {
                return this.anaquelFieldSpecified;
            }
            set {
                this.anaquelFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cantidadSistema {
            get {
                return this.cantidadSistemaField;
            }
            set {
                this.cantidadSistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSistemaSpecified {
            get {
                return this.cantidadSistemaFieldSpecified;
            }
            set {
                this.cantidadSistemaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codBodega {
            get {
                return this.codBodegaField;
            }
            set {
                this.codBodegaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codBodegaSpecified {
            get {
                return this.codBodegaFieldSpecified;
            }
            set {
                this.codBodegaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public invFisico invFisico {
            get {
                return this.invFisicoField;
            }
            set {
                this.invFisicoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public invFisicoDetPK invFisicoDetPK {
            get {
                return this.invFisicoDetPKField;
            }
            set {
                this.invFisicoDetPKField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string umedida {
            get {
                return this.umedidaField;
            }
            set {
                this.umedidaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class invFisico {
        
        private long codBodegaField;
        
        private bool codBodegaFieldSpecified;
        
        private string descripcionField;
        
        private invFisicoPK invFisicoPKField;
        
        private long totConteoField;
        
        private bool totConteoFieldSpecified;
        
        private usuario usuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codBodega {
            get {
                return this.codBodegaField;
            }
            set {
                this.codBodegaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codBodegaSpecified {
            get {
                return this.codBodegaFieldSpecified;
            }
            set {
                this.codBodegaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public invFisicoPK invFisicoPK {
            get {
                return this.invFisicoPKField;
            }
            set {
                this.invFisicoPKField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long totConteo {
            get {
                return this.totConteoField;
            }
            set {
                this.totConteoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totConteoSpecified {
            get {
                return this.totConteoFieldSpecified;
            }
            set {
                this.totConteoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class invFisicoPK {
        
        private long companiaField;
        
        private bool companiaFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private long noInventarioField;
        
        private bool noInventarioFieldSpecified;
        
        private long noListadoField;
        
        private bool noListadoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companiaSpecified {
            get {
                return this.companiaFieldSpecified;
            }
            set {
                this.companiaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long noInventario {
            get {
                return this.noInventarioField;
            }
            set {
                this.noInventarioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noInventarioSpecified {
            get {
                return this.noInventarioFieldSpecified;
            }
            set {
                this.noInventarioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long noListado {
            get {
                return this.noListadoField;
            }
            set {
                this.noListadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noListadoSpecified {
            get {
                return this.noListadoFieldSpecified;
            }
            set {
                this.noListadoFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class invFisicoDetPK {
        
        private long companiaField;
        
        private bool companiaFieldSpecified;
        
        private long correlField;
        
        private bool correlFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private long noInventarioField;
        
        private bool noInventarioFieldSpecified;
        
        private long noListadoField;
        
        private bool noListadoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companiaSpecified {
            get {
                return this.companiaFieldSpecified;
            }
            set {
                this.companiaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long correl {
            get {
                return this.correlField;
            }
            set {
                this.correlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool correlSpecified {
            get {
                return this.correlFieldSpecified;
            }
            set {
                this.correlFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long noInventario {
            get {
                return this.noInventarioField;
            }
            set {
                this.noInventarioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noInventarioSpecified {
            get {
                return this.noInventarioFieldSpecified;
            }
            set {
                this.noInventarioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long noListado {
            get {
                return this.noListadoField;
            }
            set {
                this.noListadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noListadoSpecified {
            get {
                return this.noListadoFieldSpecified;
            }
            set {
                this.noListadoFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class rol {
        
        private string descripcionField;
        
        private string idField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class empleado {
        
        private string apartadoEmailField;
        
        private string apellidoCasadaField;
        
        private string celularField;
        
        private string direccionField;
        
        private string emailField;
        
        private long estadoField;
        
        private long estadoCivilField;
        
        private short externoField;
        
        private System.DateTime fechaIngresoField;
        
        private bool fechaIngresoFieldSpecified;
        
        private string idField;
        
        private empleado jefeField;
        
        private string nombreCompletoField;
        
        private string primerApellidoField;
        
        private string primerNombreField;
        
        private string segundoApellidoField;
        
        private string segundoNombreField;
        
        private long sexoField;
        
        private string telefonoField;
        
        private string tipoSangreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apartadoEmail {
            get {
                return this.apartadoEmailField;
            }
            set {
                this.apartadoEmailField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoCasada {
            get {
                return this.apellidoCasadaField;
            }
            set {
                this.apellidoCasadaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short externo {
            get {
                return this.externoField;
            }
            set {
                this.externoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoSpecified {
            get {
                return this.fechaIngresoFieldSpecified;
            }
            set {
                this.fechaIngresoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public empleado jefe {
            get {
                return this.jefeField;
            }
            set {
                this.jefeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoSangre {
            get {
                return this.tipoSangreField;
            }
            set {
                this.tipoSangreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class compania {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.model.prueba.infosgroup.com/")]
    public partial class usuario {
        
        private long bodegaField;
        
        private bool bodegaFieldSpecified;
        
        private compania companiaField;
        
        private string descripcionField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private string idField;
        
        private rol rolField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long bodega {
            get {
                return this.bodegaField;
            }
            set {
                this.bodegaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bodegaSpecified {
            get {
                return this.bodegaFieldSpecified;
            }
            set {
                this.bodegaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public compania compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
            }
        }
    }
}
